(cl:defpackage hrwros_msgs-msg
  (:use )
  (:export
   "<COUNTERWITHDELAYACTION>"
   "COUNTERWITHDELAYACTION"
   "<COUNTERWITHDELAYACTIONFEEDBACK>"
   "COUNTERWITHDELAYACTIONFEEDBACK"
   "<COUNTERWITHDELAYACTIONGOAL>"
   "COUNTERWITHDELAYACTIONGOAL"
   "<COUNTERWITHDELAYACTIONRESULT>"
   "COUNTERWITHDELAYACTIONRESULT"
   "<COUNTERWITHDELAYFEEDBACK>"
   "COUNTERWITHDELAYFEEDBACK"
   "<COUNTERWITHDELAYGOAL>"
   "COUNTERWITHDELAYGOAL"
   "<COUNTERWITHDELAYRESULT>"
   "COUNTERWITHDELAYRESULT"
   "<SENSORINFORMATION>"
   "SENSORINFORMATION"
  ))

