(cl:defpackage hrwros_msgs-srv
  (:use )
  (:export
   "CONVERTMETERSTOFEET"
   "<CONVERTMETERSTOFEET-REQUEST>"
   "CONVERTMETERSTOFEET-REQUEST"
   "<CONVERTMETERSTOFEET-RESPONSE>"
   "CONVERTMETERSTOFEET-RESPONSE"
  ))

